---

- name: Add Google Chrome key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Add Google Chrome repository
  apt_repository: repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" state=present update_cache=yes

- name: Install Google Ghrome
  apt: name=google-chrome-stable state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
